services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.13
    container_name: swagger-peminjaman-ruang
    ports:
      - "${PORT}:8080"
    environment:
      SWAGGER_JSON: /swagger.yaml
    volumes:
      - ./swagger.yaml:/swagger.yaml
    restart: always
