services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV} # image akan menyesuaikan tergantung mode development atau production
    image: "${CONTAINER_NAME}:1.0"
    container_name: ${CONTAINER_NAME}
    # ports:
    #   - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/home/node/app
    networks:
      - peminjaman-ruang-net
    restart: always
    user: root
    command: sh -c 'npm install && if [ "$NODE_ENV" = "development" ]; then npm run start; else pm2-runtime bin/www; fi'
networks:
  peminjaman-ruang-net:
    external: true
